services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll  # This mounts your local directory inside the container
    command: jekyll serve --watch --host 0.0.0.0
